### ISSUE TITLE
No case for mechs when calculating armory points

### ISSUE THREAD

**Issue by silentdeth** [emipa606/CombatReadinessCheck#1]
ArmouryUtility.GetColonistArmouryPoints does not have a case for colony mechs.

Vanilla uses:
```
else if (p.IsColonyMech && !p.Downed)
            a = p.kindDef.combatPower * StorytellerUtility.PointsFactorForColonyMechsCurve.Evaluate(wealthForStoryteller);

```
With the curve ranging from 0.2 to 0.4. Or, put another way, 2-5x as much as animals.

Recommend adding a case for mechs, and a configuration option for mechs.

**Comment by emipa606** [comment]
Thanks, should be added in 67f2446
