### ISSUE TITLE
`MarvsMapWealthForStoryTeller` returns raid points instead of wealth

### ISSUE THREAD

**Issue by Cardds** [emipa606/CombatReadinessCheck#2]
`Map.PlayerWealthForStoryteller` is patched with `MarvsMapWealthForStoryTeller.Prefix`. However, `MarvsMapWealthForStoryTeller` does not return a wealth value, but instead returns the post-processed raid point values.

This results in massively reduced values when another source checks `PlayerWealthForStoryteller` (or an aggregation therein) that expects a wealth value.

e.g. https://github.com/Vanilla-Expanded/VanillaFactionsExpanded-Mechanoid/blob/main/1.4/Source/VFEM/Incidents/MechLandIncidents.cs#L28

**Comment by emipa606** [comment]
I see, very strange. I have changed it to only return the changed wealth values instead since the incident-prefix already recalculates the raid-points using those same functions.
Should be fixed in f9b83ce
Thanks for the info!
